export const properties = [
  {
    featured: true,
    image: "/images/property-1.jpg",
    imageAlt: "Villa Éden — villa de prestige à Riviera Golf, Abidjan",
    badge: "Coup de Cœur",
    badgeGreen: false,
    type: "Villa Prestige",
    name: "Villa Éden",
    location: "Riviera Golf, Abidjan",
    bedrooms: "6 Chambres",
    bathrooms: "5 SDB",
    area: "680 m²",
    price: "795 000 000 FCFA",
    delay: "",
  },
  {
    featured: false,
    image: "/images/property-2.jpg",
    imageAlt: "Villa Lumière — villa moderne à Cocody, Abidjan",
    badge: "Disponible",
    badgeGreen: true,
    type: "Villa Moderne",
    name: "Villa Lumière",
    location: "Cocody, Abidjan",
    bedrooms: "5 Ch.",
    bathrooms: "4 SDB",
    area: "450 m²",
    price: "485 000 000 FCFA",
    delay: "d1",
  },
  {
    featured: false,
    image: "/images/property-3.jpg",
    imageAlt: "Panorama Suite — appartement au Plateau, Abidjan",
    badge: "Neuf",
    badgeGreen: false,
    type: "Appartement",
    name: "Panorama Suite",
    location: "Le Plateau, Abidjan",
    bedrooms: "4 Ch.",
    bathrooms: "3 SDB",
    area: "220 m²",
    price: "280 000 000 FCFA",
    delay: "d2",
  },
  {
    featured: false,
    image: "/images/property-4.jpg",
    imageAlt: "Résidence Ivoire — résidence à Marcory, Abidjan",
    badge: "Disponible",
    badgeGreen: true,
    type: "Résidence",
    name: "Résidence Ivoire",
    location: "Marcory, Abidjan",
    bedrooms: "3 Ch.",
    bathrooms: "2 SDB",
    area: "150 m²",
    price: "195 000 000 FCFA",
    delay: "d3",
  },
] as const;
