import { siteImages } from "@/lib/images";

export const terrainTypes = [
  { label: "Résidentiel", count: "12 annonces" },
  { label: "Commercial", count: "5 annonces" },
  { label: "Mixte", count: "4 annonces" },
  { label: "Investissement", count: "6 annonces" },
] as const;

export const terrains = [
  {
    image: siteImages.terrains.plotCocody,
    imageAlt: "Terrain constructible à angle rue — Cocody, Abidjan",
    badge: "Coup de Cœur",
    badgeGreen: false,
    type: "Résidentiel",
    name: "Parcelle Cocody Centre",
    location: "Cocody, Abidjan",
    surface: "520 m²",
    priceM2: "45 000 FCFA/m²",
    price: "23 400 000 FCFA",
    title: "Titre foncier",
    delay: "",
  },
  {
    image: siteImages.terrains.plotRiviera,
    imageAlt: "Grand terrain avec vue panoramique — Riviera, Abidjan",
    badge: "Vue mer",
    badgeGreen: false,
    type: "Villa prestige",
    name: "Terrain Riviera Heights",
    location: "Riviera Palmeraie, Abidjan",
    surface: "1 100 m²",
    priceM2: "62 000 FCFA/m²",
    price: "68 200 000 FCFA",
    title: "Titre foncier",
    delay: "d1",
  },
  {
    image: siteImages.terrains.plotMarcory,
    imageAlt: "Terrain commercial en bordure de route — Marcory, Abidjan",
    badge: "Commercial",
    badgeGreen: true,
    type: "Commercial",
    name: "Terrain Zone 4",
    location: "Marcory, Abidjan",
    surface: "900 m²",
    priceM2: "55 000 FCFA/m²",
    price: "49 500 000 FCFA",
    title: "ACD disponible",
    delay: "d2",
  },
  {
    image: siteImages.terrains.plotAnyama,
    imageAlt: "Terrain périurbain — Anyama, Abidjan",
    badge: "Disponible",
    badgeGreen: true,
    type: "Investissement",
    name: "Parcelle Anyama Nord",
    location: "Anyama, Abidjan",
    surface: "750 m²",
    priceM2: "12 000 FCFA/m²",
    price: "9 000 000 FCFA",
    title: "Attestation villageoise",
    delay: "d3",
  },
] as const;
